start /B batch_files\smoke.bat
start /B batch_files\camera.bat
start /B batch_files\control_screen.bat
start /B batch_files\proxy.bat
start /B batch_files\movement.bat
start /B batch_files\humidity.bat
start /B batch_files\rain.bat
start /B batch_files\temperature.bat
start /B batch_files\smartlock.bat
start /B batch_files\aplicativo.bat